name: Integration tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java 
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install test requirements
        run: pip install -r requirements.txt -r test_requirements.txt
        env:
          PIP_NO_BINARY: jpy

      - name: Install collection
        run: ansible-galaxy collection install .

      - name: Run integration tests
        run: pytest tests/integration
